[package]
name = "axondb"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"       
rayon = "1.7"        
tokenizers = "0.21"   
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"        
sled = "0.34"          
linfa = "0.6"       
linfa-clustering = "0.6" 
tch = "0.19"
fieri = "0.7"
tokio = "1.43"